package com.aistudio.pinkproxy.fresh

enum class ImplementationStatus {
    IMPLEMENTED,
    STUB,
    EXPERIMENTAL,
    UNSUPPORTED,
    SIMULATED
}

enum class ValidationStatus {
    DEVICE_VERIFIED,
    EMULATOR_ONLY,
    UNVERIFIED
}

enum class BypassStrategy(
    val family: StrategyFamily = StrategyFamily.GENERIC,
    val cost: Int = 1,
    val risk: Int = 1,
    val group: StrategyGroup = StrategyGroup.MEDIUM,
    val implementationStatus: ImplementationStatus = ImplementationStatus.UNSUPPORTED,
    val validationStatus: ValidationStatus = ValidationStatus.UNVERIFIED
) {
    FAKE_PACKET(StrategyFamily.TCP, 2, 2, StrategyGroup.HEAVY, ImplementationStatus.STUB, ValidationStatus.UNVERIFIED),
    SNI_SPLIT(StrategyFamily.FRAGMENTATION, 3, 3, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    SNI_TRIPLE(StrategyFamily.FRAGMENTATION, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    SNI_MANGLE(StrategyFamily.TLS, 3, 4, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_DIRTY(StrategyFamily.TLS, 2, 3, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_PAD(StrategyFamily.TLS, 2, 2, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_GREASE(StrategyFamily.TLS, 2, 1, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_OOB_DESYNC(StrategyFamily.TCP, 4, 4, StrategyGroup.EXTREME, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    OOB_DESYNC(StrategyFamily.TCP, 4, 4, StrategyGroup.EXTREME, ImplementationStatus.SIMULATED, ValidationStatus.UNVERIFIED),
    GHOST_PACKETS(StrategyFamily.TCP, 3, 4, StrategyGroup.EXTREME, ImplementationStatus.SIMULATED, ValidationStatus.UNVERIFIED),
    SOCKET_BUFFER_MANGLE(StrategyFamily.TCP, 2, 2, StrategyGroup.MEDIUM, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_ZERO_WINDOW_STALL(StrategyFamily.TCP, 3, 3, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    SLOW_SEND(StrategyFamily.TIMING, 4, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    FRAGMENT_MULTI(StrategyFamily.FRAGMENTATION, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_REC_SPLIT(StrategyFamily.FRAGMENTATION, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_MULTI_FRAG(StrategyFamily.FRAGMENTATION, 5, 4, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_MSS_CLAMP(StrategyFamily.TCP, 3, 2, StrategyGroup.LIGHT, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TLS_EXT_SKEW(StrategyFamily.TLS, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_FAST_RETRANSMIT_SIM(StrategyFamily.TCP, 4, 4, StrategyGroup.HEAVY, ImplementationStatus.STUB, ValidationStatus.UNVERIFIED),
    TLS_REC_MANGLE(StrategyFamily.TLS, 4, 4, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_REORDER_SIM(StrategyFamily.TCP, 4, 5, StrategyGroup.EXTREME, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_FAST_OPEN_FAKE(StrategyFamily.TCP, 3, 3, StrategyGroup.MEDIUM, ImplementationStatus.STUB, ValidationStatus.UNVERIFIED),
    TLS_PADDING_RAND(StrategyFamily.TLS, 2, 2, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_HOST_SPACE(StrategyFamily.HTTP, 2, 3, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_REHANDSHAKE_FAKE(StrategyFamily.TLS, 4, 4, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_RANGE_SKEW(StrategyFamily.HTTP, 3, 3, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_RST_FAKE(StrategyFamily.TCP, 5, 5, StrategyGroup.EXTREME, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TLS_SNI_SKEW(StrategyFamily.TLS, 3, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_VERSION_SKEW(StrategyFamily.HTTP, 2, 2, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_TIMESTAMP_MANGLE(StrategyFamily.TCP, 3, 3, StrategyGroup.MEDIUM, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TLS_CIPHER_SHUFFLE(StrategyFamily.TLS, 2, 2, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_USER_AGENT_SKEW(StrategyFamily.HTTP, 2, 2, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_URGENT_RANDOM(StrategyFamily.TCP, 4, 4, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TLS_ALPN_SKEW(StrategyFamily.TLS, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_AUTH_RANDOM(StrategyFamily.HTTP, 2, 2, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_EXTENSION_GREASE(StrategyFamily.TLS, 2, 1, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_HEADER_FUZZING(StrategyFamily.HTTP, 3, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_REORDER_CHAOS(StrategyFamily.TCP, 4, 5, StrategyGroup.EXTREME, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TLS_HELLO_JUNK(StrategyFamily.TLS, 4, 4, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_METHOD_FAKE(StrategyFamily.HTTP, 3, 3, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_LEGACY_HELLOS(StrategyFamily.TLS, 3, 3, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_KEEP_ALIVE_FAKE(StrategyFamily.TCP, 2, 2, StrategyGroup.LIGHT, ImplementationStatus.STUB, ValidationStatus.UNVERIFIED),
    QUIC_RST_SKEW(StrategyFamily.QUIC, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    QUIC_MTU_PROBE(StrategyFamily.QUIC, 3, 3, StrategyGroup.MEDIUM, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    DNS_OVER_TCP(StrategyFamily.DNS, 2, 1, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    DNS_NOISE(StrategyFamily.DNS, 3, 3, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    DNS_CASE_MANGLE(StrategyFamily.DNS, 2, 2, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    ADAPTIVE_CHUNK(StrategyFamily.ADAPTIVE, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_HOST_CASE_MANGLE(StrategyFamily.HTTP, 2, 3, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_SESSION_TICKET_SKEW(StrategyFamily.TLS, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_SESSION_ID_MANGLE(StrategyFamily.TLS, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_MULTI_SNI(StrategyFamily.TLS, 4, 4, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_CHUNKED_FAKE(StrategyFamily.HTTP, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_WINDOW_RESTRICT(StrategyFamily.TCP, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TLS_COMPRESSION_FAKE(StrategyFamily.TLS, 3, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_WINDOW_SCAN(StrategyFamily.TCP, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    HTTP_PIPELINE_FAKE(StrategyFamily.HTTP, 4, 4, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_CHROME_HELLO_FAKE(StrategyFamily.TLS, 2, 1, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_FIREFOX_HELLO_FAKE(StrategyFamily.TLS, 2, 1, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_13_HELLO_FAKE(StrategyFamily.TLS, 2, 1, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_REORDER_DESYNC(StrategyFamily.TCP, 4, 4, StrategyGroup.EXTREME, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TLS_SESSION_ID_RAND(StrategyFamily.TLS, 2, 2, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_ACK_DELAY(StrategyFamily.TIMING, 4, 3, StrategyGroup.MEDIUM, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_URGENT_SKEW(StrategyFamily.TCP, 4, 4, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    SOCKET_BUFFER_SKEW(StrategyFamily.TCP, 2, 2, StrategyGroup.MEDIUM, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TLS_MIXED_CASE_SNI(StrategyFamily.TLS, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_DATA_REPETITION(StrategyFamily.TCP, 4, 2, StrategyGroup.HEAVY, ImplementationStatus.STUB, ValidationStatus.UNVERIFIED),
    TLS_SNI_SPLIT(StrategyFamily.TLS, 4, 4, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_STUN_FAKE(StrategyFamily.UDP, 2, 4, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_WINDOW_CLAMPING(StrategyFamily.TCP, 2, 2, StrategyGroup.MEDIUM, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TLS_CLIENT_HELLO_CHOP(StrategyFamily.TLS, 5, 4, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_FAKE_DTLS(StrategyFamily.UDP, 3, 4, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_FAKE_SESSION(StrategyFamily.UDP, 3, 3, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_APP_DATA_SPLIT(StrategyFamily.TLS, 4, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_HOST_MANGLE(StrategyFamily.HTTP, 3, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_FRAGMENT(StrategyFamily.HTTP, 4, 2, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_GHOST_SKEW(StrategyFamily.TCP, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.STUB, ValidationStatus.UNVERIFIED),
    TLS_CLIENT_HELLO_SHUFFLE(StrategyFamily.TLS, 5, 4, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_NOISE_PAD(StrategyFamily.UDP, 3, 4, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_RECORD_FRAGMENTATION(StrategyFamily.TLS, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    QUIC_INITIAL_FAKE(StrategyFamily.UDP, 3, 4, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_HOST_SMUGGLE(StrategyFamily.HTTP, 3, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_WIREGUARD_FAKE(StrategyFamily.UDP, 3, 3, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_IKE_FAKE(StrategyFamily.UDP, 3, 3, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_DHCP_FAKE(StrategyFamily.UDP, 3, 3, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    PROTOCOL_CONFUSION_HTTP(StrategyFamily.TCP, 3, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    PROTOCOL_CONFUSION_QUIC(StrategyFamily.UDP, 3, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    PROTOCOL_CONFUSION_DTLS(StrategyFamily.UDP, 3, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_SMALL_CHUNKS(StrategyFamily.FRAGMENTATION, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_TELEGRAM_FAKE(StrategyFamily.UDP, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_DISCORD_FAKE(StrategyFamily.UDP, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_RANDOM_PADDING(StrategyFamily.TCP, 2, 1, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_RECORD_PADDING(StrategyFamily.TLS, 2, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_HIGH_VOL_PACING(StrategyFamily.UDP, 2, 1, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_ZERO_LEN_SKEW(StrategyFamily.UDP, 2, 1, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_NOISE_CHAOS(StrategyFamily.UDP, 3, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_MSS_CLUMPING(StrategyFamily.TCP, 3, 2, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TLS_CLIENT_HELLO_GREASE_RANDOM(StrategyFamily.TLS, 2, 2, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_HOST_TAB_MANGLE(StrategyFamily.HTTP, 2, 3, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_SNI_NULL_EXT(StrategyFamily.TLS, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_CLIENT_HELLO_PAD_EXTREME(StrategyFamily.TLS, 4, 2, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_EXTENSION_SHUFFLE(StrategyFamily.TLS, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_QUIC_SKEW(StrategyFamily.UDP, 3, 3, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_DATA_FRAG(StrategyFamily.UDP, 2, 2, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_FAKE_TRAFFIC(StrategyFamily.UDP, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_IP_FRAG(StrategyFamily.UDP, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.SIMULATED, ValidationStatus.UNVERIFIED),
    QUIC_INITIAL_PADDING_EXTREME(StrategyFamily.UDP, 4, 3, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    QUIC_INITIAL_FRAGMENTATION(StrategyFamily.UDP, 5, 4, StrategyGroup.EXTREME, ImplementationStatus.SIMULATED, ValidationStatus.UNVERIFIED),
    UDP_IPv6_FRAG(StrategyFamily.UDP, 3, 3, StrategyGroup.MEDIUM, ImplementationStatus.SIMULATED, ValidationStatus.UNVERIFIED),
    ECH_FRAG(StrategyFamily.TLS, 6, 6, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    QUIC_FORCE_FRAG(StrategyFamily.UDP, 5, 5, StrategyGroup.EXTREME, ImplementationStatus.SIMULATED, ValidationStatus.UNVERIFIED),
    TCP_HANDSHAKE_CHAOS(StrategyFamily.TCP, 5, 5, StrategyGroup.EXTREME, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_MSS_CLAMPER(StrategyFamily.TCP, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    HTTP_CONNECTION_CLOSE_SKEW(StrategyFamily.HTTP, 1, 2, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_MULTI_LINE_MANGLE(StrategyFamily.HTTP, 3, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_HOST_FOLDING(StrategyFamily.HTTP, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_FRAGMENT_SKEW(StrategyFamily.UDP, 4, 4, StrategyGroup.EXTREME, ImplementationStatus.SIMULATED, ValidationStatus.UNVERIFIED),
    UDP_GHOST_SKEW(StrategyFamily.UDP, 3, 3, StrategyGroup.HEAVY, ImplementationStatus.SIMULATED, ValidationStatus.UNVERIFIED),
    TLS_SNI_SYMMETRIC_SPLIT(StrategyFamily.TLS, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_HANDSHAKE_RANDOM_PADDING(StrategyFamily.TLS, 4, 2, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_TOS_MANGLE(StrategyFamily.TCP, 2, 1, StrategyGroup.LIGHT, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TLS_GREASE_SKEW(StrategyFamily.TLS, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_CLIENT_HELLO_PAD(StrategyFamily.TLS, 3, 1, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    PROTOCOL_CONFUSION_SSH(StrategyFamily.TCP, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.SIMULATED, ValidationStatus.UNVERIFIED),
    PROTOCOL_CONFUSION_BITTORRENT(StrategyFamily.TCP, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.SIMULATED, ValidationStatus.UNVERIFIED),
    PROTOCOL_CONFUSION_REDIS(StrategyFamily.TCP, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.SIMULATED, ValidationStatus.UNVERIFIED),
    PROTOCOL_CONFUSION_MEMCACHED(StrategyFamily.TCP, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.SIMULATED, ValidationStatus.UNVERIFIED),
    WS_HANDSHAKE_FAKE(StrategyFamily.HTTP, 3, 3, StrategyGroup.MEDIUM, ImplementationStatus.SIMULATED, ValidationStatus.UNVERIFIED),
    SSH_HANDSHAKE_FAKE(StrategyFamily.TCP, 3, 3, StrategyGroup.MEDIUM, ImplementationStatus.STUB, ValidationStatus.UNVERIFIED),
    HTTP2_PREAMBLE_FAKE(StrategyFamily.HTTP, 3, 3, StrategyGroup.MEDIUM, ImplementationStatus.SIMULATED, ValidationStatus.UNVERIFIED),
    TCP_REARRANGE_CHUNKS(StrategyFamily.FRAGMENTATION, 5, 4, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TLS_0RTT_FAKE(StrategyFamily.TLS, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_DATA_OOB_SKEW(StrategyFamily.TCP, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_SACK_FAKE(StrategyFamily.TCP, 3, 3, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    HTTP_HOST_REORDER(StrategyFamily.HTTP, 2, 3, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_KEEP_ALIVE_FAKE(StrategyFamily.HTTP, 2, 2, StrategyGroup.LIGHT, ImplementationStatus.SIMULATED, ValidationStatus.UNVERIFIED),
    TLS_CLIENT_HELLO_REORDER(StrategyFamily.TLS, 4, 3, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_ECH_FAKE(StrategyFamily.TLS, 3, 3, StrategyGroup.HEAVY, ImplementationStatus.SIMULATED, ValidationStatus.UNVERIFIED),
    TCP_SEGMENT_DESYNC(StrategyFamily.TCP, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_ACK_SKEW(StrategyFamily.TCP, 2, 2, StrategyGroup.MEDIUM, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    HTTP_METHOD_CASE_MANGLE(StrategyFamily.HTTP, 2, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_ZERO_WINDOW_DESYNC(StrategyFamily.TCP, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    SOCKET_BUFFER_CHAOS(StrategyFamily.TCP, 2, 2, StrategyGroup.MEDIUM, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TLS_REC_CHOP(StrategyFamily.TLS, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_QUIC_PAD(StrategyFamily.UDP, 2, 2, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_SNI_GREASE(StrategyFamily.TLS, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    BYEBYEDPI_SIM(StrategyFamily.ADAPTIVE, 5, 4, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_OOB_SEGMENTATION(StrategyFamily.TCP, 5, 4, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_OVERLAP(StrategyFamily.TCP, 5, 5, StrategyGroup.EXTREME, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_WINDOW_SHAKE(StrategyFamily.TCP, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    QUIC_VERSION_SKEW(StrategyFamily.QUIC, 3, 3, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    UDP_HEARTBEAT(StrategyFamily.UDP, 2, 1, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_SNI_REVERSE(StrategyFamily.TLS, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_OVERLAP_SKEW(StrategyFamily.TCP, 4, 4, StrategyGroup.EXTREME, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    QUIC_INITIAL_FRAGMENT(StrategyFamily.QUIC, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_SNI_OVERLAP_SKEW(StrategyFamily.TLS, 5, 5, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_METHOD_SPACE_MANGLE(StrategyFamily.HTTP, 2, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_HOST_DOT_MANGLE(StrategyFamily.HTTP, 2, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_WINDOW_RESIZE_PACING(StrategyFamily.TCP, 3, 3, StrategyGroup.MEDIUM, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_KEEPALIVE_SKEW(StrategyFamily.TCP, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.STUB, ValidationStatus.UNVERIFIED),
    TCP_URGENT_DESYNC(StrategyFamily.TCP, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_SYN_FLOOD_FAKE(StrategyFamily.TCP, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TLS_CLIENT_HELLO_MULTI_PAD(StrategyFamily.TLS, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_HEADER_CASE_CHAOS(StrategyFamily.HTTP, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    QUIC_HANDSHAKE_SKEW(StrategyFamily.QUIC, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_DATA_DESYNC(StrategyFamily.TCP, 5, 5, StrategyGroup.EXTREME, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_ACK_SKEW_ADVANCED(StrategyFamily.TCP, 3, 3, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    BYEBYEDPI_HYBRID(StrategyFamily.ADAPTIVE, 6, 5, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    BYEBYEDPI_EXTREME(StrategyFamily.ADAPTIVE, 6, 5, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    ZAPRET_EXTREME(StrategyFamily.ADAPTIVE, 6, 5, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_QUIC_SMART_SHADOW(StrategyFamily.QUIC, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_DNS_REORDER_HYBRID(StrategyFamily.DNS, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_REORDER(StrategyFamily.UDP, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    UDP_SKEW_ADVANCED(StrategyFamily.UDP, 4, 4, StrategyGroup.EXTREME, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    DNS_OVER_TCP_FORCE(StrategyFamily.DNS, 2, 1, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_IP_ID_MANGLE(StrategyFamily.UDP, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_FOOL_DPI(StrategyFamily.TCP, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.SIMULATED, ValidationStatus.UNVERIFIED),
    TCP_BYTE_FRAG(StrategyFamily.FRAGMENTATION, 5, 4, StrategyGroup.EXTREME, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_REVERSE_FRAG(StrategyFamily.TCP, 5, 4, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_DATA_DESYNC_OVERLAP(StrategyFamily.TCP, 6, 5, StrategyGroup.EXTREME, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_FRAGMENT_REORDER(StrategyFamily.TCP, 8, 5, StrategyGroup.EXTREME, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    UDP_SKEW_REVERSE(StrategyFamily.UDP, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_RETRANS_FAKE(StrategyFamily.TCP, 5, 4, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    SOCKET_BUFFER_JITTER(StrategyFamily.TCP, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TLS_SNI_JITTER_SPLIT(StrategyFamily.TLS, 5, 4, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_SNI_EXT_MANGLE(StrategyFamily.TLS, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_QUIC_JITTER_PAD(StrategyFamily.UDP, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_SNI_FRAGMENT(StrategyFamily.FRAGMENTATION, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_TLS_SESSION_DESYNC(StrategyFamily.TCP, 5, 4, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    SOCKET_BUFFER_OSCILLATION(StrategyFamily.TCP, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_SACK_PANIC(StrategyFamily.TCP, 6, 5, StrategyGroup.EXTREME, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_SACK_SKEW(StrategyFamily.TCP, 5, 4, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TLS_SNI_SKEW_ADVANCED(StrategyFamily.TLS, 6, 6, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TLS_EXT_CHAOS(StrategyFamily.TLS, 5, 5, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_HEADER_MANGLE(StrategyFamily.HTTP, 2, 1, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_LINE_SPLIT(StrategyFamily.HTTP, 3, 2, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    HTTP_HOST_REVERSE(StrategyFamily.HTTP, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_TRIPLE_DESYNC(StrategyFamily.TCP, 6, 5, StrategyGroup.EXTREME, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_FAKE_FIN(StrategyFamily.TCP, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    UDP_BURST_CHAOS(StrategyFamily.UDP, 5, 4, StrategyGroup.EXTREME, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    UDP_REPLICATION(StrategyFamily.UDP, 3, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_STUTTER(StrategyFamily.UDP, 2, 2, StrategyGroup.LIGHT, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    UDP_PADDING_CHAOS(StrategyFamily.UDP, 5, 5, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    CHAOS(StrategyFamily.ADAPTIVE, 9, 9, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_WINDOW_SHRINK(StrategyFamily.TCP, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_WINDOW_STALL(StrategyFamily.TCP, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_ZERO_WINDOW_OOB(StrategyFamily.TCP, 5, 4, StrategyGroup.EXTREME, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_TIMING_CHAOS(StrategyFamily.TCP, 4, 3, StrategyGroup.MEDIUM, ImplementationStatus.SIMULATED, ValidationStatus.UNVERIFIED),
    TCP_TLS_HELLO_FRAGMENT(StrategyFamily.TCP, 5, 4, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_TLS_SNI_CASE_MOD(StrategyFamily.TCP, 4, 3, StrategyGroup.MEDIUM, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_OVERLAP_SKEW(StrategyFamily.UDP, 5, 4, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_REORDER(StrategyFamily.TCP, 4, 3, StrategyGroup.MEDIUM, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_COMBINED_HYBRID(StrategyFamily.ADAPTIVE, 10, 8, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_COMBINED_HYBRID(StrategyFamily.ADAPTIVE, 8, 7, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_COMBINED_NUCLEAR(StrategyFamily.ADAPTIVE, 12, 10, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_COMBINED_NUCLEAR(StrategyFamily.ADAPTIVE, 12, 10, StrategyGroup.EXTREME, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    ECH_GREASE(StrategyFamily.TLS, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    TCP_SEGMENT_OVERLAP(StrategyFamily.TCP, 5, 4, StrategyGroup.EXTREME, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    UDP_QUIC_CHAOS(StrategyFamily.QUIC, 6, 5, StrategyGroup.EXTREME, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_SEGMENT_REVERSE(StrategyFamily.TCP, 5, 4, StrategyGroup.EXTREME, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    DOH_OVER_QUIC(StrategyFamily.DNS, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    TCP_PULSE_FRAG(StrategyFamily.FRAGMENTATION, 5, 3, StrategyGroup.HEAVY, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED),
    UDP_RACING(StrategyFamily.QUIC, 6, 5, StrategyGroup.EXTREME, ImplementationStatus.SIMULATED, ValidationStatus.UNVERIFIED),
    UDP_FAKE_PACKET(StrategyFamily.UDP, 3, 3, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    UDP_FRAGMENTATION(StrategyFamily.UDP, 4, 3, StrategyGroup.HEAVY, ImplementationStatus.UNSUPPORTED, ValidationStatus.UNVERIFIED),
    DIRECT(StrategyFamily.DIRECT, 0, 0, StrategyGroup.LIGHT, ImplementationStatus.IMPLEMENTED, ValidationStatus.UNVERIFIED)
}
